version: '3'

services:
  reactjs:
    build: 
        context: ./frontend/iot-app
        dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  java_spring:
    build: 
        context: ./backend/IotSensorArt
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3005:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana

  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data: {}
  grafana: {}
